
[functions.accurate-list-so]
enabled = true
verify_jwt = true
import_map = "./functions/accurate-list-so/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/accurate-list-so/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/accurate-list-so/*.html" ]

[functions.accurate-detail-so]
enabled = true
verify_jwt = true
import_map = "./functions/accurate-detail-so/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/accurate-detail-so/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/accurate-detail-so/*.html" ]

[functions.accurate-print-doc]
enabled = true
verify_jwt = true
import_map = "./functions/accurate-print-doc/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/accurate-print-doc/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/accurate-print-doc/*.html" ]

[functions.accurate-list-tracking-so]
enabled = true
verify_jwt = true
import_map = "./functions/accurate-list-tracking-so/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/accurate-list-tracking-so/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/accurate-list-tracking-so/*.html" ]

[functions.temp-migration]
enabled = true
verify_jwt = true
import_map = "./functions/temp-migration/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/temp-migration/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/temp-migration/*.html" ]

[functions.temp-migration-hso]
enabled = true
verify_jwt = true
import_map = "./functions/temp-migration-hso/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/temp-migration-hso/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/temp-migration-hso/*.html" ]
